name        : hicolor-icon-theme
version     : 0.17
release     : 7
source      :
    - https://icon-theme.freedesktop.org/releases/hicolor-icon-theme-0.17.tar.xz : 317484352271d18cbbcfac3868eab798d67fff1b8402e740baa6ff41d588a9d8
homepage    : http://www.freedesktop.org/wiki/Software/icon-theme/
license     :
    - GPL-2.0
summary     : Default fallback icon theme
component   : desktop.theme
description : |
    The hicolor-icon-theme package contains a default fallback theme for implementations of the icon theme specification.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
